site_name: Edenlab Playbook
nav:
  - Home: index.md
  - API Design: api-design.md
  - Reading List: reading-list.md
  - Collaboration Rules: collaboration_rules.md
  - Architecture Decision Records (ADR):
      - Overview: architecture-decisions/overview.md
      - When Should I Write an Architecture Decision Record: architecture-decisions/when-should-i-write-an-architecture-decision-record.md
  - Testing: testing.md
  - Fullstack Team: fullstack-team.md
  - Guides:
      - Overview: guides.md
      - Languages:
          - JavaScript: style-guide/javascript.md
          - TypeScript: style-guide/typescript.md
          - Go: style-guide/go.md
      - Frameworks and platforms:
          - React: style-guide/react.md
          - React Native: style-guide/react-native.md
          - Testing with Jest: style-guide/testing-jest.md
      - Tools:
          - GraphQL: style-guide/graphql.md

plugins:
  - techdocs-core
